using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WAD.Doom
{
    public static class Infos
    {
        public enum Sprite
        {
            TROO,
            SHTG,
            PUNG,
            PISG,
            PISF,
            SHTF,
            SHT2,
            CHGG,
            CHGF,
            MISG,
            MISF,
            SAWG,
            PLSG,
            PLSF,
            BFGG,
            BFGF,
            BLUD,
            PUFF,
            BAL1,
            BAL2,
            PLSS,
            PLSE,
            MISL,
            BFS1,
            BFE1,
            BFE2,
            TFOG,
            IFOG,
            PLAY,
            POSS,
            SPOS,
            VILE,
            FIRE,
            FATB,
            FBXP,
            SKEL,
            MANF,
            FATT,
            CPOS,
            SARG,
            HEAD,
            BAL7,
            BOSS,
            BOS2,
            SKUL,
            SPID,
            BSPI,
            APLS,
            APBX,
            CYBR,
            PAIN,
            SSWV,
            KEEN,
            BBRN,
            BOSF,
            ARM1,
            ARM2,
            BAR1,
            BEXP,
            FCAN,
            BON1,
            BON2,
            BKEY,
            RKEY,
            YKEY,
            BSKU,
            RSKU,
            YSKU,
            STIM,
            MEDI,
            SOUL,
            PINV,
            PSTR,
            PINS,
            MEGA,
            SUIT,
            PMAP,
            PVIS,
            CLIP,
            AMMO,
            ROCK,
            BROK,
            CELL,
            CELP,
            SHEL,
            SBOX,
            BPAK,
            BFUG,
            MGUN,
            CSAW,
            LAUN,
            PLAS,
            SHOT,
            SGN2,
            COLU,
            SMT2,
            GOR1,
            POL2,
            POL5,
            POL4,
            POL3,
            POL1,
            POL6,
            GOR2,
            GOR3,
            GOR4,
            GOR5,
            SMIT,
            COL1,
            COL2,
            COL3,
            COL4,
            CAND,
            CBRA,
            COL6,
            TRE1,
            TRE2,
            ELEC,
            CEYE,
            FSKU,
            COL5,
            TBLU,
            TGRN,
            TRED,
            SMBT,
            SMGT,
            SMRT,
            HDB1,
            HDB2,
            HDB3,
            HDB4,
            HDB5,
            HDB6,
            POB1,
            POB2,
            BRS1,
            TLMP,
            TLP2,
            Count
        }

        public static Dictionary<Sprite, string> SpriteNames = new Dictionary<Sprite, string>
        {
            { Sprite.TROO, "TROO" },
            { Sprite.SHTG, "SHTG" },
            { Sprite.PUNG, "PUNG" },
            { Sprite.PISG, "PISG" },
            { Sprite.PISF, "PISF" },
            { Sprite.SHTF, "SHTF" },
            { Sprite.SHT2, "SHT2" },
            { Sprite.CHGG, "CHGG" },
            { Sprite.CHGF, "CHGF" },
            { Sprite.MISG, "MISG" },
            { Sprite.MISF, "MISF" },
            { Sprite.SAWG, "SAWG" },
            { Sprite.PLSG, "PLSG" },
            { Sprite.PLSF, "PLSF" },
            { Sprite.BFGG, "BFGG" },
            { Sprite.BFGF, "BFGF" },
            { Sprite.BLUD, "BLUD" },
            { Sprite.PUFF, "PUFF" },
            { Sprite.BAL1, "BAL1" },
            { Sprite.BAL2, "BAL2" },
            { Sprite.PLSS, "PLSS" },
            { Sprite.PLSE, "PLSE" },
            { Sprite.MISL, "MISL" },
            { Sprite.BFS1, "BFS1" },
            { Sprite.BFE1, "BFE1" },
            { Sprite.BFE2, "BFE2" },
            { Sprite.TFOG, "TFOG" },
            { Sprite.IFOG, "IFOG" },
            { Sprite.PLAY, "PLAY" },
            { Sprite.POSS, "POSS" },
            { Sprite.SPOS, "SPOS" },
            { Sprite.VILE, "VILE" },
            { Sprite.FIRE, "FIRE" },
            { Sprite.FATB, "FATB" },
            { Sprite.FBXP, "FBXP" },
            { Sprite.SKEL, "SKEL" },
            { Sprite.MANF, "MANF" },
            { Sprite.FATT, "FATT" },
            { Sprite.CPOS, "CPOS" },
            { Sprite.SARG, "SARG" },
            { Sprite.HEAD, "HEAD" },
            { Sprite.BAL7, "BAL7" },
            { Sprite.BOSS, "BOSS" },
            { Sprite.BOS2, "BOS2" },
            { Sprite.SKUL, "SKUL" },
            { Sprite.SPID, "SPID" },
            { Sprite.BSPI, "BSPI" },
            { Sprite.APLS, "APLS" },
            { Sprite.APBX, "APBX" },
            { Sprite.CYBR, "CYBR" },
            { Sprite.PAIN, "PAIN" },
            { Sprite.SSWV, "SSWV" },
            { Sprite.KEEN, "KEEN" },
            { Sprite.BBRN, "BBRN" },
            { Sprite.BOSF, "BOSF" },
            { Sprite.ARM1, "ARM1" },
            { Sprite.ARM2, "ARM2" },
            { Sprite.BAR1, "BAR1" },
            { Sprite.BEXP, "BEXP" },
            { Sprite.FCAN, "FCAN" },
            { Sprite.BON1, "BON1" },
            { Sprite.BON2, "BON2" },
            { Sprite.BKEY, "BKEY" },
            { Sprite.RKEY, "RKEY" },
            { Sprite.YKEY, "YKEY" },
            { Sprite.BSKU, "BSKU" },
            { Sprite.RSKU, "RSKU" },
            { Sprite.YSKU, "YSKU" },
            { Sprite.STIM, "STIM" },
            { Sprite.MEDI, "MEDI" },
            { Sprite.SOUL, "SOUL" },
            { Sprite.PINV, "PINV" },
            { Sprite.PSTR, "PSTR" },
            { Sprite.PINS, "PINS" },
            { Sprite.MEGA, "MEGA" },
            { Sprite.SUIT, "SUIT" },
            { Sprite.PMAP, "PMAP" },
            { Sprite.PVIS, "PVIS" },
            { Sprite.CLIP, "CLIP" },
            { Sprite.AMMO, "AMMO" },
            { Sprite.ROCK, "ROCK" },
            { Sprite.BROK, "BROK" },
            { Sprite.CELL, "CELL" },
            { Sprite.CELP, "CELP" },
            { Sprite.SHEL, "SHEL" },
            { Sprite.SBOX, "SBOX" },
            { Sprite.BPAK, "BPAK" },
            { Sprite.BFUG, "BFUG" },
            { Sprite.MGUN, "MGUN" },
            { Sprite.CSAW, "CSAW" },
            { Sprite.LAUN, "LAUN" },
            { Sprite.PLAS, "PLAS" },
            { Sprite.SHOT, "SHOT" },
            { Sprite.SGN2, "SGN2" },
            { Sprite.COLU, "COLU" },
            { Sprite.SMT2, "SMT2" },
            { Sprite.GOR1, "GOR1" },
            { Sprite.POL2, "POL2" },
            { Sprite.POL5, "POL5" },
            { Sprite.POL4, "POL4" },
            { Sprite.POL3, "POL3" },
            { Sprite.POL1, "POL1" },
            { Sprite.POL6, "POL6" },
            { Sprite.GOR2, "GOR2" },
            { Sprite.GOR3, "GOR3" },
            { Sprite.GOR4, "GOR4" },
            { Sprite.GOR5, "GOR5" },
            { Sprite.SMIT, "SMIT" },
            { Sprite.COL1, "COL1" },
            { Sprite.COL2, "COL2" },
            { Sprite.COL3, "COL3" },
            { Sprite.COL4, "COL4" },
            { Sprite.CAND, "CAND" },
            { Sprite.CBRA, "CBRA" },
            { Sprite.COL6, "COL6" },
            { Sprite.TRE1, "TRE1" },
            { Sprite.TRE2, "TRE2" },
            { Sprite.ELEC, "ELEC" },
            { Sprite.CEYE, "CEYE" },
            { Sprite.FSKU, "FSKU" },
            { Sprite.COL5, "COL5" },
            { Sprite.TBLU, "TBLU" },
            { Sprite.TGRN, "TGRN" },
            { Sprite.TRED, "TRED" },
            { Sprite.SMBT, "SMBT" },
            { Sprite.SMGT, "SMGT" },
            { Sprite.SMRT, "SMRT" },
            { Sprite.HDB1, "HDB1" },
            { Sprite.HDB2, "HDB2" },
            { Sprite.HDB3, "HDB3" },
            { Sprite.HDB4, "HDB4" },
            { Sprite.HDB5, "HDB5" },
            { Sprite.HDB6, "HDB6" },
            { Sprite.POB1, "POB1" },
            { Sprite.POB2, "POB2" },
            { Sprite.BRS1, "BRS1" },
            { Sprite.TLMP, "TLMP" },
            { Sprite.TLP2, "TLP2" }
        };

        public enum Bgm
        {
            NONE,
            E1M1,
            E1M2,
            E1M3,
            E1M4,
            E1M5,
            E1M6,
            E1M7,
            E1M8,
            E1M9,
            E2M1,
            E2M2,
            E2M3,
            E2M4,
            E2M5,
            E2M6,
            E2M7,
            E2M8,
            E2M9,
            E3M1,
            E3M2,
            E3M3,
            E3M4,
            E3M5,
            E3M6,
            E3M7,
            E3M8,
            E3M9,
            INTER,
            INTRO,
            BUNNY,
            VICTOR,
            INTROA,
            RUNNIN,
            STALKS,
            COUNTD,
            BETWEE,
            DOOM,
            THE_DA,
            SHAWN,
            DDTBLU,
            IN_CIT,
            DEAD,
            STLKS2,
            THEDA2,
            DOOM2,
            DDTBL2,
            RUNNI2,
            DEAD2,
            STLKS3,
            ROMERO,
            SHAWN2,
            MESSAG,
            COUNT2,
            DDTBL3,
            AMPIE,
            THEDA3,
            ADRIAN,
            MESSG2,
            ROMER2,
            TENSE,
            SHAWN3,
            OPENIN,
            EVIL,
            ULTIMA,
            READ_M,
            DM2TTL,
            DM2INT,
            Count
        }

        public static Dictionary<Bgm, string> BGMNames = new Dictionary<Bgm, string>
        {
            { Bgm.NONE, "none" },
            { Bgm.E1M1, "e1m1"},
            { Bgm.E1M2, "e1m2"},
            { Bgm.E1M3, "e1m3"},
            { Bgm.E1M4, "e1m4"},
            { Bgm.E1M5, "e1m5"},
            { Bgm.E1M6, "e1m6"},
            { Bgm.E1M7, "e1m7"},
            { Bgm.E1M8, "e1m8"},
            { Bgm.E1M9, "e1m9"},
            { Bgm.E2M1, "e2m1"},
            { Bgm.E2M2, "e2m2"},
            { Bgm.E2M3, "e2m3"},
            { Bgm.E2M4, "e2m4"},
            { Bgm.E2M5, "e2m5"},
            { Bgm.E2M6, "e2m6"},
            { Bgm.E2M7, "e2m7"},
            { Bgm.E2M8, "e2m8"},
            { Bgm.E2M9, "e2m9"},
            { Bgm.E3M1, "e3m1"},
            { Bgm.E3M2, "e3m2"},
            { Bgm.E3M3, "e3m3"},
            { Bgm.E3M4, "e3m4"},
            { Bgm.E3M5, "e3m5"},
            { Bgm.E3M6, "e3m6"},
            { Bgm.E3M7, "e3m7"},
            { Bgm.E3M8, "e3m8"},
            { Bgm.E3M9, "e3m9"},
            { Bgm.INTER, "inter"},
            { Bgm.INTRO, "intro"},
            { Bgm.BUNNY, "bunny"},
            { Bgm.VICTOR, "victor"},
            { Bgm.INTROA, "introa"},
            { Bgm.RUNNIN, "runnin"},
            { Bgm.STALKS, "stalks"},
            { Bgm.COUNTD, "countd"},
            { Bgm.BETWEE, "betwee"},
            { Bgm.DOOM, "doom"},
            { Bgm.THE_DA, "the_da"},
            { Bgm.SHAWN, "shawn"},
            { Bgm.DDTBLU, "ddtblu"},
            { Bgm.IN_CIT, "in_cit"},
            { Bgm.DEAD, "dead"},
            { Bgm.STLKS2, "stlks2"},
            { Bgm.THEDA2, "theda2"},
            { Bgm.DOOM2, "doom2"},
            { Bgm.DDTBL2, "ddtbl2"},
            { Bgm.RUNNI2, "runni2"},
            { Bgm.DEAD2, "dead2"},
            { Bgm.STLKS3, "stlks3"},
            { Bgm.ROMERO, "romero"},
            { Bgm.SHAWN2, "shawn2"},
            { Bgm.MESSAG, "messag"},
            { Bgm.COUNT2, "count2"},
            { Bgm.DDTBL3, "ddtbl3"},
            { Bgm.AMPIE, "ampie"},
            { Bgm.THEDA3, "theda3"},
            { Bgm.ADRIAN, "adrian"},
            { Bgm.MESSG2, "messg2"},
            { Bgm.ROMER2, "romer2"},
            { Bgm.TENSE, "tense"},
            { Bgm.SHAWN3, "shawn3"},
            { Bgm.OPENIN, "openin"},
            { Bgm.EVIL, "evil"},
            { Bgm.ULTIMA, "ultima"},
            { Bgm.READ_M, "read_m"},
            { Bgm.DM2TTL, "dm2ttl"},
            { Bgm.DM2INT, "dm2int"}
        };

        public enum Sfx
        {
            NONE,
            PISTOL,
            SHOTGN,
            SGCOCK,
            DSHTGN,
            DBOPN,
            DBCLS,
            DBLOAD,
            PLASMA,
            BFG,
            SAWUP,
            SAWIDL,
            SAWFUL,
            SAWHIT,
            RLAUNC,
            RXPLOD,
            FIRSHT,
            FIRXPL,
            PSTART,
            PSTOP,
            DOROPN,
            DORCLS,
            STNMOV,
            SWTCHN,
            SWTCHX,
            PLPAIN,
            DMPAIN,
            POPAIN,
            VIPAIN,
            MNPAIN,
            PEPAIN,
            SLOP,
            ITEMUP,
            WPNUP,
            OOF,
            TELEPT,
            POSIT1,
            POSIT2,
            POSIT3,
            BGSIT1,
            BGSIT2,
            SGTSIT,
            CACSIT,
            BRSSIT,
            CYBSIT,
            SPISIT,
            BSPSIT,
            KNTSIT,
            VILSIT,
            MANSIT,
            PESIT,
            SKLATK,
            SGTATK,
            SKEPCH,
            VILATK,
            CLAW,
            SKESWG,
            PLDETH,
            PDIEHI,
            PODTH1,
            PODTH2,
            PODTH3,
            BGDTH1,
            BGDTH2,
            SGTDTH,
            CACDTH,
            SKLDTH,
            BRSDTH,
            CYBDTH,
            SPIDTH,
            BSPDTH,
            VILDTH,
            KNTDTH,
            PEDTH,
            SKEDTH,
            POSACT,
            BGACT,
            DMACT,
            BSPACT,
            BSPWLK,
            VILACT,
            NOWAY,
            BAREXP,
            PUNCH,
            HOOF,
            METAL,
            CHGUN,
            TINK,
            BDOPN,
            BDCLS,
            ITMBK,
            FLAME,
            FLAMST,
            GETPOW,
            BOSPIT,
            BOSCUB,
            BOSSIT,
            BOSPN,
            BOSDTH,
            MANATK,
            MANDTH,
            SSSIT,
            SSDTH,
            KEENPN,
            KEENDT,
            SKEACT,
            SKESIT,
            SKEATK,
            RADIO,
            Count
        }

        public static Dictionary<Sfx, string> SFXNames = new Dictionary<Sfx, string>
        {
            { Sfx.NONE, "none"},
            { Sfx.PISTOL, "pistol"},
            { Sfx.SHOTGN, "shotgn"},
            { Sfx.SGCOCK, "sgcock"},
            { Sfx.DSHTGN, "dshtgn"},
            { Sfx.DBOPN, "dbopn"},
            { Sfx.DBCLS, "dbcls"},
            { Sfx.DBLOAD, "dbload"},
            { Sfx.PLASMA, "plasma"},
            { Sfx.BFG, "bfg"},
            { Sfx.SAWUP, "sawup"},
            { Sfx.SAWIDL, "sawidl"},
            { Sfx.SAWFUL, "sawful"},
            { Sfx.SAWHIT, "sawhit"},
            { Sfx.RLAUNC, "rlaunc"},
            { Sfx.RXPLOD, "rxplod"},
            { Sfx.FIRSHT, "firsht"},
            { Sfx.FIRXPL, "firxpl"},
            { Sfx.PSTART, "pstart"},
            { Sfx.PSTOP, "pstop"},
            { Sfx.DOROPN, "doropn"},
            { Sfx.DORCLS, "dorcls"},
            { Sfx.STNMOV, "stnmov"},
            { Sfx.SWTCHN, "swtchn"},
            { Sfx.SWTCHX, "swtchx"},
            { Sfx.PLPAIN, "plpain"},
            { Sfx.DMPAIN, "dmpain"},
            { Sfx.POPAIN, "popain"},
            { Sfx.VIPAIN, "vipain"},
            { Sfx.MNPAIN, "mnpain"},
            { Sfx.PEPAIN, "pepain"},
            { Sfx.SLOP, "slop"},
            { Sfx.ITEMUP, "itemup"},
            { Sfx.WPNUP, "wpnup"},
            { Sfx.OOF, "oof"},
            { Sfx.TELEPT, "telept"},
            { Sfx.POSIT1, "posit1"},
            { Sfx.POSIT2, "posit2"},
            { Sfx.POSIT3, "posit3"},
            { Sfx.BGSIT1, "bgsit1"},
            { Sfx.BGSIT2, "bgsit2"},
            { Sfx.SGTSIT, "sgtsit"},
            { Sfx.CACSIT, "cacsit"},
            { Sfx.BRSSIT, "brssit"},
            { Sfx.CYBSIT, "cybsit"},
            { Sfx.SPISIT, "spisit"},
            { Sfx.BSPSIT, "bspsit"},
            { Sfx.KNTSIT, "kntsit"},
            { Sfx.VILSIT, "vilsit"},
            { Sfx.MANSIT, "mansit"},
            { Sfx.PESIT, "pesit"},
            { Sfx.SKLATK, "sklatk"},
            { Sfx.SGTATK, "sgtatk"},
            { Sfx.SKEPCH, "skepch"},
            { Sfx.VILATK, "vilatk"},
            { Sfx.CLAW, "claw"},
            { Sfx.SKESWG, "skeswg"},
            { Sfx.PLDETH, "pldeth"},
            { Sfx.PDIEHI, "pdiehi"},
            { Sfx.PODTH1, "podth1"},
            { Sfx.PODTH2, "podth2"},
            { Sfx.PODTH3, "podth3"},
            { Sfx.BGDTH1, "bgdth1"},
            { Sfx.BGDTH2, "bgdth2"},
            { Sfx.SGTDTH, "sgtdth"},
            { Sfx.CACDTH, "cacdth"},
            { Sfx.SKLDTH, "skldth"},
            { Sfx.BRSDTH, "brsdth"},
            { Sfx.CYBDTH, "cybdth"},
            { Sfx.SPIDTH, "spidth"},
            { Sfx.BSPDTH, "bspdth"},
            { Sfx.VILDTH, "vildth"},
            { Sfx.KNTDTH, "kntdth"},
            { Sfx.PEDTH, "pedth"},
            { Sfx.SKEDTH, "skedth"},
            { Sfx.POSACT, "posact"},
            { Sfx.BGACT, "bgact"},
            { Sfx.DMACT, "dmact"},
            { Sfx.BSPACT, "bspact"},
            { Sfx.BSPWLK, "bspwlk"},
            { Sfx.VILACT, "vilact"},
            { Sfx.NOWAY, "noway"},
            { Sfx.BAREXP, "barexp"},
            { Sfx.PUNCH, "punch"},
            { Sfx.HOOF, "hoof"},
            { Sfx.METAL, "metal"},
            { Sfx.CHGUN, "chgun"},
            { Sfx.TINK, "tink"},
            { Sfx.BDOPN, "bdopn"},
            { Sfx.BDCLS, "bdcls"},
            { Sfx.ITMBK, "itmbk"},
            { Sfx.FLAME, "flame"},
            { Sfx.FLAMST, "flamst"},
            { Sfx.GETPOW, "getpow"},
            { Sfx.BOSPIT, "bospit"},
            { Sfx.BOSCUB, "boscub"},
            { Sfx.BOSSIT, "bossit"},
            { Sfx.BOSPN, "bospn"},
            { Sfx.BOSDTH, "bosdth"},
            { Sfx.MANATK, "manatk"},
            { Sfx.MANDTH, "mandth"},
            { Sfx.SSSIT, "sssit"},
            { Sfx.SSDTH, "ssdth"},
            { Sfx.KEENPN, "keenpn"},
            { Sfx.KEENDT, "keendt"},
            { Sfx.SKEACT, "skeact"},
            { Sfx.SKESIT, "skesit"},
            { Sfx.SKEATK, "skeatk"},
            { Sfx.RADIO, "radio"}
        };
    }
}
